In [1]:
import prueba_sencilla as pb
import pandas as pd

df_vegans_SN = pb.obtenerTodo("Vegan Restaurant", "San Francisco")
df_vegans_SN

,Name,City,Coordinates,Geometry
0,Wildseed,San Francisco,"[-122.432446, 37.797643]","{'Type': 'Point', 'coordinates': [-122.432446,..."
1,Shizen Vegan Sushi Bar & Izakaya,San Francisco,"[-122.421642, 37.768314]","{'Type': 'Point', 'coordinates': [-122.421642,..."
2,Nick's on Mission,San Francisco,"[-122.4087, 37.78128]","{'Type': 'Point', 'coordinates': [-122.4087, 3..."
3,Gracias Madre,San Francisco,"[-122.419241, 37.761606]","{'Type': 'Point', 'coordinates': [-122.419241,..."
4,Greens Restaurant,San Francisco,"[-122.432264, 37.8053224]","{'Type': 'Point', 'coordinates': [-122.432264,..."
5,Crêpe Hearts,San Francisco,"[-122.42023, 37.7796]","{'Type': 'Point', 'coordinates': [-122.42023, ..."
6,VeganBurg,San Francisco,"[-122.44646, 37.77017]","{'Type': 'Point', 'coordinates': [-122.44646, ..."
7,Golden Era Vegan Restaurant,San Francisco,"[-122.416835837066, 37.7814734450825]","{'Type': 'Point', 'coordinates': [-122.4168358..."
8,Vegan Picnic,San Francisco,"[-122.43163, 37.79734]","{'Type': 'Point', 'coordinates': [-122.43163, ..."
9,Nourish Cafe,San Francisco,"[-122.4647598, 37.7852478]","{'Type': 'Point', 'coordinates': [-122.4647598..."
10,Peña Pachamama,San Francisco,"[-122.41049, 37.79976]","{'Type': 'Point', 'coordinates': [-122.41049, ..."
11,Loving Hut,San Francisco,"[-122.46361, 37.76442]","{'Type': 'Point', 'coordinates': [-122.46361, ..."
12,Ananda Fuara,San Francisco,"[-122.4162, 37.77798]","{'Type': 'Point', 'coordinates': [-122.4162, 3..."
13,Indochine Vegan,San Francisco,"[-122.421955168247, 37.7646623774103]","{'Type': 'Point', 'coordinates': [-122.4219551..."
14,Next Level Burger,San Francisco,"[-122.4032778, 37.7644788]","{'Type': 'Point', 'coordinates': [-122.4032778..."
15,Cha-Ya,San Francisco,"[-122.421787, 37.760753]","{'Type': 'Point', 'coordinates': [-122.421787,..."
16,Namu Stonepot - Dolores Park,San Francisco,"[-122.425898, 37.761566]","{'Type': 'Point', 'coordinates': [-122.425898,..."
17,CyBelle's Front Room,San Francisco,"[-122.46641, 37.76238]","{'Type': 'Point', 'coordinates': [-122.46641, ..."
18,Vegan Mob,Oakland,"[-122.247057, 37.810572]","{'Type': 'Point', 'coordinates': [-122.247057,..."
19,Konomama,San Francisco,"[-122.468708712617, 37.7807500854503]","{'Type': 'Point', 'coordinates': [-122.4687087..."
20,Animal Place's Vegan Republic,Berkeley,"[-122.279272, 37.870588]","{'Type': 'Point', 'coordinates': [-122.279272,..."
21,Palmetto Superfoods,San Francisco,"[-122.4614, 37.78333]","{'Type': 'Point', 'coordinates': [-122.4614, 3..."
22,Bizza,San Francisco,"[-122.44645, 37.76994]","{'Type': 'Point', 'coordinates': [-122.44645, ..."
23,The Flying Falafel,San Francisco,"[-122.411304, 37.7812488]","{'Type': 'Point', 'coordinates': [-122.411304,..."
24,The Butchers Son,Berkeley,"[-122.271646200946, 37.8715428393541]","{'Type': 'Point', 'coordinates': [-122.2716462..."
25,Mission Curry House,San Francisco,"[-122.41928, 37.75796]","{'Type': 'Point', 'coordinates': [-122.41928, ..."
26,Kitava,San Francisco,"[-122.4193, 37.76483]","{'Type': 'Point', 'coordinates': [-122.4193, 3..."
27,Souley Vegan,Oakland,"[-122.2760079, 37.7969452]","{'Type': 'Point', 'coordinates': [-122.2760079..."
28,Vegan Picnic,San Francisco,"[-122.42062, 37.78892]","{'Type': 'Point', 'coordinates': [-122.42062, ..."
29,Rose Indian Cuisine,San Francisco,"[-122.465914, 37.762469]","{'Type': 'Point', 'coordinates': [-122.465914,..."
30,Thai Idea Vegetarian,San Francisco,"[-122.4190575, 37.7834938]","{'Type': 'Point', 'coordinates': [-122.4190575..."
31,MaMo,San Francisco,"[-122.43366, 37.80384]","{'Type': 'Point', 'coordinates': [-122.43366, ..."
32,Urban Remedy,San Francisco,"[-122.42905, 37.75184]","{'Type': 'Point', 'coordinates': [-122.42905, ..."
33,Loving Hut,San Francisco,"[-122.406015, 37.784308]","{'Type': 'Point', 'coordinates': [-122.406015,..."
34,Judahlicious,San Francisco,"[-122.50408, 37.76068]","{'Type': 'Point', 'coordinates': [-122.50408, ..."
35,Roz Ka Affaire,San Francisco,"[-122.402529, 37.776657]","{'Type': 'Point', 'coordinates': [-122.402529,..."
36,Lucky Creation Vegetarian Restaurant,San Francisco,"[-122.407378596858, 37.7951059659376]","{'Type': 'Point', 'coordinates': [-122.4073785..."
37,Inle Burmese Cuisine,San Francisco,"[-122.427493333333, 37.7504635620095]","{'Type': 'Point', 'coordinates': [-122.4274933..."
38,Moya,San Francisco,"[-122.414074, 37.776067]","{'Type': 'Point', 'coordinates': [-122.414074,..."
39,Vegan Alien,Berkeley,"[-122.279207, 37.870592]","{'Type': 'Point', 'coordinates': [-122.279207,..."
40,Millennium,Oakland,"[-122.2519112, 37.8475302]","{'Type': 'Point', 'coordinates': [-122.2519112..."
41,Chisme Cantina,San Francisco,"[-122.41483, 37.78862]","{'Type': 'Point', 'coordinates': [-122.41483, ..."
42,Gay 4 U,Oakland,"[-122.26884, 37.80476]","{'Type': 'Point', 'coordinates': [-122.26884, ..."
43,Donut Farm,San Francisco,"[-122.393124103546, 37.7952541103275]","{'Type': 'Point', 'coordinates': [-122.3931241..."
44,Nick's On Grand,South San Francisco,"[-122.409045464279, 37.6548012278022]","{'Type': 'Point', 'coordinates': [-122.4090454..."
45,Potala Vegan Restaurant,Albany,"[-122.2969, 37.88503]","{'Type': 'Point', 'coordinates': [-122.2969, 3..."
46,Oasis Cafe,San Francisco,"[-122.438572457672, 37.7778538803103]","{'Type': 'Point', 'coordinates': [-122.4385724..."
47,Shangri-La Vegan,Oakland,"[-122.2767442, 37.8312072]","{'Type': 'Point', 'coordinates': [-122.2767442..."
48,Enjoy Vegetarian Restaurant,San Francisco,"[-122.469100952148, 37.760425567627]","{'Type': 'Point', 'coordinates': [-122.4691009..."
49,The House,San Francisco,"[-122.40706, 37.79851]","{'Type': 'Point', 'coordinates': [-122.40706, ..."

In [2]:
df_vegans_NY = pb.obtenerTodo("Vegan Restaurant", "New york")
df_vegans_NY

,Name,City,Coordinates,Geometry
0,Blossom,New York,"[-74.002365, 40.745513]","{'Type': 'Point', 'coordinates': [-74.002365, ..."
1,MTHR Vegan,New York,"[-73.98806, 40.76241]","{'Type': 'Point', 'coordinates': [-73.98806, 4..."
2,XYST,New York,"[-73.99444, 40.73874]","{'Type': 'Point', 'coordinates': [-73.99444, 4..."
3,Jajaja,New York,"[-73.9904247969389, 40.7141530317142]","{'Type': 'Point', 'coordinates': [-73.99042479..."
4,Jajaja,New York,"[-74.00455, 40.72979]","{'Type': 'Point', 'coordinates': [-74.00455, 4..."
5,by CHLOE,New York,"[-74.001021, 40.729219]","{'Type': 'Point', 'coordinates': [-74.001021, ..."
6,Born N Bred,Brooklyn,"[-73.90979833, 40.67647667]","{'Type': 'Point', 'coordinates': [-73.90979833..."
7,Urban Vegan Kitchen,New York,"[-74.00368, 40.7302]","{'Type': 'Point', 'coordinates': [-74.00368, 4..."
8,Divya's Kitchen,New York,"[-73.98849, 40.72378]","{'Type': 'Point', 'coordinates': [-73.98849, 4..."
9,Red Bamboo,New York,"[-74.0003546456233, 40.7313183707867]","{'Type': 'Point', 'coordinates': [-74.00035464..."
10,Spicy Moon,New York,"[-73.98722, 40.72674]","{'Type': 'Point', 'coordinates': [-73.98722, 4..."
11,Avant Garden,New York,"[-73.98402, 40.7261499]","{'Type': 'Point', 'coordinates': [-73.98402, 4..."
12,Ladybird,New York,"[-73.9847712789363, 40.726769311104]","{'Type': 'Point', 'coordinates': [-73.98477127..."
13,Dirt Candy,New York,"[-73.9907183, 40.7179075]","{'Type': 'Point', 'coordinates': [-73.9907183,..."
14,Seasoned Vegan,New York,"[-73.952757, 40.800664]","{'Type': 'Point', 'coordinates': [-73.952757, ..."
15,Patty Wagon Express,Brooklyn,"[-73.9693814, 40.6967725]","{'Type': 'Point', 'coordinates': [-73.9693814,..."
16,Greedi Vegan,Brooklyn,"[-73.9523247, 40.6763513]","{'Type': 'Point', 'coordinates': [-73.9523247,..."
17,Zen Yai Pho Noodle Bar,Brooklyn,"[-73.960337, 40.713897]","{'Type': 'Point', 'coordinates': [-73.960337, ..."
18,Candle 79,New York,"[-73.958697, 40.774627]","{'Type': 'Point', 'coordinates': [-73.958697, ..."
19,Modern Love Brooklyn,Brooklyn,"[-73.95109, 40.70983]","{'Type': 'Point', 'coordinates': [-73.95109, 4..."
20,Greedi Kitchen,Brooklyn,"[-73.9230186, 40.683581]","{'Type': 'Point', 'coordinates': [-73.9230186,..."
21,Jujube Tree,Astoria,"[-73.91821, 40.76512]","{'Type': 'Point', 'coordinates': [-73.91821, 4..."
22,Petisco Vegano,New York,"[-73.988805, 40.713928]","{'Type': 'Point', 'coordinates': [-73.988805, ..."
23,Franchia Vegan Cafe,New York,"[-73.9812423408763, 40.7474712051298]","{'Type': 'Point', 'coordinates': [-73.98124234..."
24,Le Botaniste,New York,"[-74.0002028, 40.7204278]","{'Type': 'Point', 'coordinates': [-74.0002028,..."
25,Champs Diner,Brooklyn,"[-73.9407808520115, 40.7084397372605]","{'Type': 'Point', 'coordinates': [-73.94078085..."
26,Frangos Peri Peri,New York,"[-73.979444, 40.727787]","{'Type': 'Point', 'coordinates': [-73.979444, ..."
27,Nix,New York,"[-73.99359, 40.73323]","{'Type': 'Point', 'coordinates': [-73.99359, 4..."
28,Peacefood Cafe Downtown,New York,"[-73.9929751334153, 40.7332670924819]","{'Type': 'Point', 'coordinates': [-73.99297513..."
29,Happy Zoe Vegan Bakery,Brooklyn,"[-73.949646, 40.724233]","{'Type': 'Point', 'coordinates': [-73.949646, ..."
30,P.S. Kitchen,New York,"[-73.98664, 40.76066]","{'Type': 'Point', 'coordinates': [-73.98664, 4..."
31,Blossom on Columbus,New York,"[-73.9728638, 40.7853146]","{'Type': 'Point', 'coordinates': [-73.9728638,..."
32,Bar Verde,New York,"[-73.9897361397743, 40.7260849061034]","{'Type': 'Point', 'coordinates': [-73.98973613..."
33,Honeybee’s,New York,"[-73.98403, 40.72563]","{'Type': 'Point', 'coordinates': [-73.98403, 4..."
34,Delice & Sarrasin,New York,"[-74.00065, 40.73377]","{'Type': 'Point', 'coordinates': [-74.00065, 4..."
35,Vegan Love,New York,"[-73.9832536018494, 40.7285173652335]","{'Type': 'Point', 'coordinates': [-73.98325360..."
36,Original Buddha Bodai Kosher Vegetarian Restau...,New York,"[-73.9989484, 40.7138543]","{'Type': 'Point', 'coordinates': [-73.9989484,..."
37,VSPOT,Brooklyn,"[-73.9795, 40.67808]","{'Type': 'Point', 'coordinates': [-73.9795, 40..."
38,ABCV,New York,"[-73.9888740099824, 40.7379039812942]","{'Type': 'Point', 'coordinates': [-73.98887400..."
39,TRI Lounge & Cafe,Staten Island,"[-74.0868073, 40.606095404]","{'Type': 'Point', 'coordinates': [-74.0868073,..."
40,Jungle Cafe,Brooklyn,"[-73.954885, 40.730358]","{'Type': 'Point', 'coordinates': [-73.954885, ..."
41,Govinda's Vegetarian,Brooklyn,"[-73.98241, 40.68771]","{'Type': 'Point', 'coordinates': [-73.98241, 4..."
42,Ital Kitchen,Brooklyn,"[-73.95804, 40.66962]","{'Type': 'Point', 'coordinates': [-73.95804, 4..."
43,Hangawi,New York,"[-73.984662, 40.746737]","{'Type': 'Point', 'coordinates': [-73.984662, ..."
44,GLUR Thai,New York,"[-73.99665, 40.74121]","{'Type': 'Point', 'coordinates': [-73.99665, 4..."
45,Vegan Shop Up,Brooklyn,"[-73.9328064747926, 40.7054685975945]","{'Type': 'Point', 'coordinates': [-73.93280647..."
46,Double Zero,New York,"[-73.9896645, 40.7261288]","{'Type': 'Point', 'coordinates': [-73.9896645,..."
47,Pure Ktchn,New York,"[-73.98992, 40.76053]","{'Type': 'Point', 'coordinates': [-73.98992, 4..."
48,Zooba,New York,"[-73.997309692204, 40.7212932028146]","{'Type': 'Point', 'coordinates': [-73.99730969..."
49,The Candle Cafe,New York,"[-73.959146, 40.771434]","{'Type': 'Point', 'coordinates': [-73.959146, ..."

In [3]:
df_vegans_SE = pb.obtenerTodo("Vegan Restaurant", "seattle")
df_vegans_SE

,Name,City,Coordinates,Geometry
0,Plum Bistro,Seattle,"[-122.3171839, 47.6137675]","{'Type': 'Point', 'coordinates': [-122.3171839..."
1,Harvest Beat,Seattle,"[-122.33678, 47.66115]","{'Type': 'Point', 'coordinates': [-122.33678, ..."
2,Wayward Vegan Cafe,Seattle,"[-122.3198, 47.6757]","{'Type': 'Point', 'coordinates': [-122.3198, 4..."
3,No Bones Beach Club,Seattle,"[-122.3786058, 47.6683552]","{'Type': 'Point', 'coordinates': [-122.3786058..."
4,Cafe Flora,Seattle,"[-122.29521, 47.62397]","{'Type': 'Point', 'coordinates': [-122.29521, ..."
5,Celest Cafe,Seattle,"[-122.34418, 47.71256]","{'Type': 'Point', 'coordinates': [-122.34418, ..."
6,Veggie Grill,Seattle,"[-122.3365793, 47.6098539]","{'Type': 'Point', 'coordinates': [-122.3365793..."
7,Vegan Haven,Seattle,"[-122.31267, 47.66837]","{'Type': 'Point', 'coordinates': [-122.31267, ..."
8,Galaxy Rune,Seattle,"[-122.35031, 47.65169]","{'Type': 'Point', 'coordinates': [-122.35031, ..."
9,Kati Vegan Thai,Seattle,"[-122.33343, 47.62096]","{'Type': 'Point', 'coordinates': [-122.33343, ..."
10,Araya's Place,Seattle,"[-122.2960954, 47.6238626]","{'Type': 'Point', 'coordinates': [-122.2960954..."
11,Next Level Burger,Seattle,"[-122.31642, 47.67513]","{'Type': 'Point', 'coordinates': [-122.31642, ..."
12,Highline Bar,Seattle,"[-122.32067, 47.6203]","{'Type': 'Point', 'coordinates': [-122.32067, ..."
13,Cycle Dogs,Seattle,"[-122.37703, 47.6639]","{'Type': 'Point', 'coordinates': [-122.37703, ..."
14,Pizza Pi Vegan Pizzeria,Seattle,"[-122.312872, 47.6686016]","{'Type': 'Point', 'coordinates': [-122.312872,..."
15,Bang Bang Café,Seattle,"[-122.3493, 47.6140199]","{'Type': 'Point', 'coordinates': [-122.3493, 4..."
16,Loving Hut,Seattle,"[-122.31609, 47.5993799]","{'Type': 'Point', 'coordinates': [-122.31609, ..."
17,Secret Savory,Seattle,"[-122.3854, 47.6685]","{'Type': 'Point', 'coordinates': [-122.3854, 4..."
18,HeartBeet Organic Superfoods Cafe,Seattle,"[-122.357367, 47.63459]","{'Type': 'Point', 'coordinates': [-122.357367,..."
19,ChuMinh Tofu & Vegan Deli,Seattle,"[-122.3177822, 47.5989179]","{'Type': 'Point', 'coordinates': [-122.3177822..."
20,Araya's Place,Seattle,"[-122.3128845, 47.6675671]","{'Type': 'Point', 'coordinates': [-122.3128845..."
21,Oak,Seattle,"[-122.31001, 47.5764]","{'Type': 'Point', 'coordinates': [-122.31001, ..."
22,Flying Apron,Seattle,"[-122.3497053, 47.6509412]","{'Type': 'Point', 'coordinates': [-122.3497053..."
23,Bounty Kitchen,Seattle,"[-122.3565216, 47.6381912]","{'Type': 'Point', 'coordinates': [-122.3565216..."
24,Araya's Place Bellevue,Bellevue,"[-122.203256897628, 47.6103170155624]","{'Type': 'Point', 'coordinates': [-122.2032568..."
25,El Borracho,Seattle,"[-122.34076, 47.60934]","{'Type': 'Point', 'coordinates': [-122.34076, ..."
26,Blossom Vegetarian,Renton,"[-122.20848, 47.479386]","{'Type': 'Point', 'coordinates': [-122.20848, ..."
27,Life On Mars,Seattle,"[-122.32234, 47.614246]","{'Type': 'Point', 'coordinates': [-122.32234, ..."
28,Brown Sugar Baking Company,Seattle,"[-122.30296, 47.59985]","{'Type': 'Point', 'coordinates': [-122.30296, ..."
29,Asian Cajun Vegan,Seattle,"[-122.309651747346, 47.5769208468127]","{'Type': 'Point', 'coordinates': [-122.3096517..."
30,Noodle Time Noodle Eatery,Seattle,"[-122.325665, 47.618676]","{'Type': 'Point', 'coordinates': [-122.325665,..."
31,Emmy's Vege House,Bainbridge Island,"[-122.5212097, 47.6250038]","{'Type': 'Point', 'coordinates': [-122.5212097..."
32,Veggie Grill,Seattle,"[-122.336923465408, 47.6229080378028]","{'Type': 'Point', 'coordinates': [-122.3369234..."
33,Broadfork Cafe,Seattle,"[-122.31556, 47.66474]","{'Type': 'Point', 'coordinates': [-122.31556, ..."
34,The Cookie Counter,Seattle,"[-122.3555681, 47.6830855]","{'Type': 'Point', 'coordinates': [-122.3555681..."
35,Mighty-O Donuts,Seattle,"[-122.333258, 47.668804]","{'Type': 'Point', 'coordinates': [-122.333258,..."
36,Silence-Heart-Nest,Seattle,"[-122.3502, 47.65083]","{'Type': 'Point', 'coordinates': [-122.3502, 4..."
37,Moonlight Cafe,Seattle,"[-122.30672, 47.59901]","{'Type': 'Point', 'coordinates': [-122.30672, ..."
38,I Love My GFF,Seattle,"[-122.336994657105, 47.6243996044122]","{'Type': 'Point', 'coordinates': [-122.3369946..."
39,Seattle Lotus Vegetarian Restaurant,Seattle,"[-122.355625364418, 47.5088066528403]","{'Type': 'Point', 'coordinates': [-122.3556253..."
40,Plum Pantry,Seattle,"[-122.350826365051, 47.621416407533]","{'Type': 'Point', 'coordinates': [-122.3508263..."
41,Redwing Cafe,Seattle,"[-122.26139, 47.51956]","{'Type': 'Point', 'coordinates': [-122.26139, ..."
42,Tilth,Seattle,"[-122.34006, 47.66116]","{'Type': 'Point', 'coordinates': [-122.34006, ..."
43,Cafe Pettirosso,Seattle,"[-122.31792964418, 47.6138316046163]","{'Type': 'Point', 'coordinates': [-122.3179296..."
44,Eggs & Plants,Seattle,"[-122.3429413, 47.6156197]","{'Type': 'Point', 'coordinates': [-122.3429413..."
45,Cypher Cafe / Washington Hall,Seattle,"[-122.31459, 47.60285]","{'Type': 'Point', 'coordinates': [-122.31459, ..."
46,Veggie Grill,Seattle,"[-122.2986458, 47.6632151]","{'Type': 'Point', 'coordinates': [-122.2986458..."
47,Bamboo Garden Vegetarian Cuisine,Seattle,"[-122.34941, 47.62559]","{'Type': 'Point', 'coordinates': [-122.34941, ..."
48,Sprout,Seattle,"[-122.332066488718, 47.6020821770476]","{'Type': 'Point', 'coordinates': [-122.3320664..."
49,Eden Hill Restaurant,Seattle,"[-122.35715, 47.63876]","{'Type': 'Point', 'coordinates': [-122.35715, ..."

In [7]:
df_vegans =df_vegans_SN.append(df_vegans_NY)
df_vegans

,Name,City,Coordinates,Geometry
0,Wildseed,San Francisco,"[-122.432446, 37.797643]","{'Type': 'Point', 'coordinates': [-122.432446,..."
1,Shizen Vegan Sushi Bar & Izakaya,San Francisco,"[-122.421642, 37.768314]","{'Type': 'Point', 'coordinates': [-122.421642,..."
2,Nick's on Mission,San Francisco,"[-122.4087, 37.78128]","{'Type': 'Point', 'coordinates': [-122.4087, 3..."
3,Gracias Madre,San Francisco,"[-122.419241, 37.761606]","{'Type': 'Point', 'coordinates': [-122.419241,..."
4,Greens Restaurant,San Francisco,"[-122.432264, 37.8053224]","{'Type': 'Point', 'coordinates': [-122.432264,..."
...,...,...,...,...
45,Vegan Shop Up,Brooklyn,"[-73.9328064747926, 40.7054685975945]","{'Type': 'Point', 'coordinates': [-73.93280647..."
46,Double Zero,New York,"[-73.9896645, 40.7261288]","{'Type': 'Point', 'coordinates': [-73.9896645,..."
47,Pure Ktchn,New York,"[-73.98992, 40.76053]","{'Type': 'Point', 'coordinates': [-73.98992, 4..."
48,Zooba,New York,"[-73.997309692204, 40.7212932028146]","{'Type': 'Point', 'coordinates': [-73.99730969..."
49,The Candle Cafe,New York,"[-73.959146, 40.771434]","{'Type': 'Point', 'coordinates': [-73.959146, ..."

In [8]:
df_vegans= df_vegans.append(df_vegans_SE)
df_vegans

,Name,City,Coordinates,Geometry
0,Wildseed,San Francisco,"[-122.432446, 37.797643]","{'Type': 'Point', 'coordinates': [-122.432446,..."
1,Shizen Vegan Sushi Bar & Izakaya,San Francisco,"[-122.421642, 37.768314]","{'Type': 'Point', 'coordinates': [-122.421642,..."
2,Nick's on Mission,San Francisco,"[-122.4087, 37.78128]","{'Type': 'Point', 'coordinates': [-122.4087, 3..."
3,Gracias Madre,San Francisco,"[-122.419241, 37.761606]","{'Type': 'Point', 'coordinates': [-122.419241,..."
4,Greens Restaurant,San Francisco,"[-122.432264, 37.8053224]","{'Type': 'Point', 'coordinates': [-122.432264,..."
...,...,...,...,...
45,Cypher Cafe / Washington Hall,Seattle,"[-122.31459, 47.60285]","{'Type': 'Point', 'coordinates': [-122.31459, ..."
46,Veggie Grill,Seattle,"[-122.2986458, 47.6632151]","{'Type': 'Point', 'coordinates': [-122.2986458..."
47,Bamboo Garden Vegetarian Cuisine,Seattle,"[-122.34941, 47.62559]","{'Type': 'Point', 'coordinates': [-122.34941, ..."
48,Sprout,Seattle,"[-122.332066488718, 47.6020821770476]","{'Type': 'Point', 'coordinates': [-122.3320664..."
49,Eden Hill Restaurant,Seattle,"[-122.35715, 47.63876]","{'Type': 'Point', 'coordinates': [-122.35715, ..."

In [9]:
type(df_vegans.to_dict('split'))

dict

In [10]:
import json
df_vegans.to_json("./vegans.json", orient = "records")

In [11]:
from pymongo import MongoClient
import pandas as pd
import json as js

mongo_client = MongoClient('localhost', 27017)

# create new database and client collection
db= mongo_client["companies"]

db.create_collection("vegans")

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'companies'), 'vegans')

In [12]:
df_veg_coord=df_vegans["Coordinates"]

In [14]:
df_coord_veg=pd.DataFrame(df_veg_coord)
df_coord_veg

                              Coordinates
0                [-122.432446, 37.797643]
1                [-122.421642, 37.768314]
2                   [-122.4087, 37.78128]
3                [-122.419241, 37.761606]
4               [-122.432264, 37.8053224]
..                                    ...
45                 [-122.31459, 47.60285]
46             [-122.2986458, 47.6632151]
47                 [-122.34941, 47.62559]
48  [-122.332066488718, 47.6020821770476]
49                 [-122.35715, 47.63876]

[150 rows x 1 columns]

In [15]:
df_coord_veg.to_csv("coord_veg")

In [ ]:
df.rename(columns = {'$b':'B'}, inplace = True)