In [50]:
import prueba_sencilla as pb
import pandas as pd

df_starbucks_SN = pb.obtenerTodo("Starbucks", "San Francisco")
df_starbucks_SN

,Name,City,Coordinates,Geometry
0,Starbucks,San Francisco,"[-122.434666, 37.761019]","{'Type': 'Point', 'coordinates': [-122.434666,..."
1,Starbucks,San Francisco,"[-122.431709, 37.751341]","{'Type': 'Point', 'coordinates': [-122.431709,..."
2,Starbucks,San Francisco,"[-122.428353, 37.769122]","{'Type': 'Point', 'coordinates': [-122.428353,..."
3,Starbucks,San Francisco,"[-122.456377, 37.7641418236607]","{'Type': 'Point', 'coordinates': [-122.456377,..."
4,Starbucks,San Francisco,"[-122.446293, 37.775737]","{'Type': 'Point', 'coordinates': [-122.446293,..."
5,Starbucks,San Francisco,"[-122.438964, 37.74359]","{'Type': 'Point', 'coordinates': [-122.438964,..."
6,Starbucks,San Francisco,"[-122.45256, 37.74455]","{'Type': 'Point', 'coordinates': [-122.45256, ..."
7,Starbucks,San Francisco,"[-122.410423, 37.762912]","{'Type': 'Point', 'coordinates': [-122.410423,..."
8,Starbucks,San Francisco,"[-122.417368, 37.777208]","{'Type': 'Point', 'coordinates': [-122.417368,..."
9,Starbucks,San Francisco,"[-122.409623, 37.766884]","{'Type': 'Point', 'coordinates': [-122.409623,..."
10,Starbucks,San Francisco,"[-122.445631, 37.7817834575863]","{'Type': 'Point', 'coordinates': [-122.445631,..."
11,Starbucks,San Francisco,"[-122.432907, 37.78341]","{'Type': 'Point', 'coordinates': [-122.432907,..."
12,Starbucks,San Francisco,"[-122.44708, 37.782074]","{'Type': 'Point', 'coordinates': [-122.44708, ..."
13,Starbucks,San Francisco,"[-122.447186721606, 37.7821128080096]","{'Type': 'Point', 'coordinates': [-122.4471867..."
14,Starbucks,San Francisco,"[-122.466024, 37.764205]","{'Type': 'Point', 'coordinates': [-122.466024,..."
15,Starbucks,San Francisco,"[-122.415038, 37.778262]","{'Type': 'Point', 'coordinates': [-122.415038,..."
16,Starbucks,San Francisco,"[-122.439858, 37.785936]","{'Type': 'Point', 'coordinates': [-122.439858,..."
17,Starbucks,San Francisco,"[-122.403495, 37.76589]","{'Type': 'Point', 'coordinates': [-122.403495,..."
18,Starbucks,San Francisco,"[-122.403461, 37.770246]","{'Type': 'Point', 'coordinates': [-122.403461,..."
19,Starbucks,San Francisco,"[-122.434696, 37.788618]","{'Type': 'Point', 'coordinates': [-122.434696,..."
20,Starbucks,San Francisco,"[-122.453194, 37.786261]","{'Type': 'Point', 'coordinates': [-122.453194,..."
21,Starbucks,San Francisco,"[-122.433979, 37.7902085]","{'Type': 'Point', 'coordinates': [-122.433979,..."
22,Starbucks,San Francisco,"[-122.422216, 37.788575]","{'Type': 'Point', 'coordinates': [-122.422216,..."
23,Starbucks,San Francisco,"[-122.422065, 37.790218]","{'Type': 'Point', 'coordinates': [-122.422065,..."
24,Starbucks,San Francisco,"[-122.4673386, 37.739714]","{'Type': 'Point', 'coordinates': [-122.4673386..."
25,Starbucks,San Francisco,"[-122.477411, 37.763689]","{'Type': 'Point', 'coordinates': [-122.477411,..."
26,Starbucks,San Francisco,"[-122.407653, 37.784124]","{'Type': 'Point', 'coordinates': [-122.407653,..."
27,Starbucks,San Francisco,"[-122.410691, 37.787326]","{'Type': 'Point', 'coordinates': [-122.410691,..."
28,Starbucks,San Francisco,"[-122.409094, 37.78615]","{'Type': 'Point', 'coordinates': [-122.409094,..."
29,Starbucks,San Francisco,"[-122.408225, 37.786528]","{'Type': 'Point', 'coordinates': [-122.408225,..."
30,Starbucks,San Francisco,"[-122.393893, 37.767102]","{'Type': 'Point', 'coordinates': [-122.393893,..."
31,Starbucks,San Francisco,"[-122.404157, 37.784166]","{'Type': 'Point', 'coordinates': [-122.404157,..."
32,Starbucks,San Francisco,"[-122.407329, 37.78702]","{'Type': 'Point', 'coordinates': [-122.407329,..."
33,Starbucks,San Francisco,"[-122.40385, 37.7844609656521]","{'Type': 'Point', 'coordinates': [-122.40385, ..."
34,Starbucks,San Francisco,"[-122.405723, 37.786139]","{'Type': 'Point', 'coordinates': [-122.405723,..."
35,Starbucks,San Francisco,"[-122.408456, 37.789145]","{'Type': 'Point', 'coordinates': [-122.408456,..."
36,Starbucks,San Francisco,"[-122.396701, 37.77867]","{'Type': 'Point', 'coordinates': [-122.396701,..."
37,Starbucks,San Francisco,"[-122.406831, 37.789338331116]","{'Type': 'Point', 'coordinates': [-122.406831,..."
38,Starbucks,San Francisco,"[-122.430395, 37.797644]","{'Type': 'Point', 'coordinates': [-122.430395,..."
39,Starbucks,San Francisco,"[-122.394074, 37.776819]","{'Type': 'Point', 'coordinates': [-122.394074,..."
40,Starbucks,San Francisco,"[-122.40322, 37.7873985]","{'Type': 'Point', 'coordinates': [-122.40322, ..."
41,Starbucks,San Francisco,"[-122.393641, 37.777035]","{'Type': 'Point', 'coordinates': [-122.393641,..."
42,Starbucks,San Francisco,"[-122.39996, 37.784833]","{'Type': 'Point', 'coordinates': [-122.39996, ..."
43,Starbucks,San Francisco,"[-122.422096, 37.796758]","{'Type': 'Point', 'coordinates': [-122.422096,..."
44,Starbucks,San Francisco,"[-122.4034092, 37.78846142]","{'Type': 'Point', 'coordinates': [-122.4034092..."
45,Starbucks,San Francisco,"[-122.47805, 37.78008]","{'Type': 'Point', 'coordinates': [-122.47805, ..."
46,Starbucks,San Francisco,"[-122.40576, 37.7904291]","{'Type': 'Point', 'coordinates': [-122.40576, ..."
47,Starbucks,San Francisco,"[-122.389293971144, 37.771251]","{'Type': 'Point', 'coordinates': [-122.3892939..."
48,Starbucks,San Francisco,"[-122.401087, 37.787764]","{'Type': 'Point', 'coordinates': [-122.401087,..."
49,Starbucks,San Francisco,"[-122.40386, 37.790697]","{'Type': 'Point', 'coordinates': [-122.40386, ..."

In [51]:
df_starbucks_NY = pb.obtenerTodo("Starbucks", "New York")
df_starbucks_NY

,Name,City,Coordinates,Geometry
0,Starbucks,Brooklyn,"[-73.993666, 40.702818]","{'Type': 'Point', 'coordinates': [-73.993666, ..."
1,Starbucks,Brooklyn,"[-73.990806294802, 40.702668]","{'Type': 'Point', 'coordinates': [-73.99080629..."
2,Starbucks,New York,"[-74.000916, 40.711018]","{'Type': 'Point', 'coordinates': [-74.000916, ..."
3,Starbucks,New York,"[-74.004971, 40.707122]","{'Type': 'Point', 'coordinates': [-74.004971, ..."
4,Starbucks,New York,"[-74.006685, 40.706487]","{'Type': 'Point', 'coordinates': [-74.006685, ..."
5,Starbucks,New York,"[-74.007159, 40.7047907]","{'Type': 'Point', 'coordinates': [-74.007159, ..."
6,Starbucks,New York,"[-74.007387, 40.708413]","{'Type': 'Point', 'coordinates': [-74.007387, ..."
7,Starbucks,Brooklyn,"[-73.993978, 40.694582]","{'Type': 'Point', 'coordinates': [-73.993978, ..."
8,Starbucks,New York,"[-74.008696, 40.706155]","{'Type': 'Point', 'coordinates': [-74.008696, ..."
9,Starbucks,New York,"[-74.009001, 40.704653]","{'Type': 'Point', 'coordinates': [-74.009001, ..."
10,Starbucks,New York,"[-74.006730001524, 40.711619]","{'Type': 'Point', 'coordinates': [-74.00673000..."
11,Starbucks,New York,"[-74.00799, 40.71018]","{'Type': 'Point', 'coordinates': [-74.00799, 4..."
12,Starbucks,New York,"[-74.009313, 40.708771]","{'Type': 'Point', 'coordinates': [-74.009313, ..."
13,Starbucks,New York,"[-74.008533, 40.710792]","{'Type': 'Point', 'coordinates': [-74.008533, ..."
14,Starbucks,New York,"[-74.003125, 40.715754]","{'Type': 'Point', 'coordinates': [-74.003125, ..."
15,Starbucks,New York,"[-74.008202, 40.712214]","{'Type': 'Point', 'coordinates': [-74.008202, ..."
16,Starbucks,Brooklyn,"[-73.9867893, 40.694047]","{'Type': 'Point', 'coordinates': [-73.9867893,..."
17,Starbucks,New York,"[-74.010976, 40.707437]","{'Type': 'Point', 'coordinates': [-74.010976, ..."
18,Starbucks,New York,"[-74.01133, 40.705162]","{'Type': 'Point', 'coordinates': [-74.01133, 4..."
19,Starbucks,New York,"[-74.005956, 40.714843]","{'Type': 'Point', 'coordinates': [-74.005956, ..."
20,Starbucks,New York,"[-74.011055, 40.708758]","{'Type': 'Point', 'coordinates': [-74.011055, ..."
21,Starbucks,Brooklyn,"[-73.991201, 40.692464]","{'Type': 'Point', 'coordinates': [-73.991201, ..."
22,Starbucks,New York,"[-74.010363, 40.71091]","{'Type': 'Point', 'coordinates': [-74.010363, ..."
23,Starbucks,New York,"[-73.999961, 40.718252]","{'Type': 'Point', 'coordinates': [-73.999961, ..."
24,Starbucks,Brooklyn,"[-73.982911, 40.694975]","{'Type': 'Point', 'coordinates': [-73.982911, ..."
25,Starbucks,New York,"[-74.012051, 40.702149]","{'Type': 'Point', 'coordinates': [-74.012051, ..."
26,Starbucks,New York,"[-74.009077, 40.713782]","{'Type': 'Point', 'coordinates': [-74.009077, ..."
27,Starbucks,New York,"[-74.011793, 40.710372]","{'Type': 'Point', 'coordinates': [-74.011793, ..."
28,Starbucks,New York,"[-74.01087, 40.712117]","{'Type': 'Point', 'coordinates': [-74.01087, 4..."
29,Starbucks,New York,"[-74.012733, 40.702775]","{'Type': 'Point', 'coordinates': [-74.012733, ..."
30,Starbucks,Brooklyn,"[-73.988548, 40.691795]","{'Type': 'Point', 'coordinates': [-73.988548, ..."
31,Starbucks,New York,"[-74.0130866, 40.704345]","{'Type': 'Point', 'coordinates': [-74.0130866,..."
32,Starbucks,New York,"[-73.989977, 40.7193246]","{'Type': 'Point', 'coordinates': [-73.989977, ..."
33,Starbucks,New York,"[-74.013011, 40.706894]","{'Type': 'Point', 'coordinates': [-74.013011, ..."
34,Starbucks,New York,"[-74.002524, 40.718887]","{'Type': 'Point', 'coordinates': [-74.002524, ..."
35,Starbucks,New York,"[-73.99913, 40.719757]","{'Type': 'Point', 'coordinates': [-73.99913, 4..."
36,Starbucks,New York,"[-74.009003, 40.715532]","{'Type': 'Point', 'coordinates': [-74.009003, ..."
37,Starbucks,New York,"[-74.014093, 40.703281]","{'Type': 'Point', 'coordinates': [-74.014093, ..."
38,Starbucks,New York,"[-74.014155, 40.709198]","{'Type': 'Point', 'coordinates': [-74.014155, ..."
39,Starbucks,Brooklyn,"[-73.984355, 40.691567]","{'Type': 'Point', 'coordinates': [-73.984355, ..."
40,Starbucks,Brooklyn,"[-73.98632603, 40.69074857]","{'Type': 'Point', 'coordinates': [-73.98632603..."
41,Starbucks,New York,"[-74.007305, 40.718247]","{'Type': 'Point', 'coordinates': [-74.007305, ..."
42,Starbucks,New York,"[-74.004979, 40.719887439843]","{'Type': 'Point', 'coordinates': [-74.004979, ..."
43,Starbucks,Brooklyn,"[-73.98254, 40.691174]","{'Type': 'Point', 'coordinates': [-73.98254, 4..."
44,Starbucks,Brooklyn,"[-73.992748, 40.688556]","{'Type': 'Point', 'coordinates': [-73.992748, ..."
45,Starbucks,New York,"[-74.015373, 40.710914]","{'Type': 'Point', 'coordinates': [-74.015373, ..."
46,Starbucks,New York,"[-73.997942, 40.722553]","{'Type': 'Point', 'coordinates': [-73.997942, ..."
47,Starbucks,Brooklyn,"[-73.98563, 40.68921]","{'Type': 'Point', 'coordinates': [-73.98563, 4..."
48,Starbucks Reserve,New York,"[-74.015465, 40.713821]","{'Type': 'Point', 'coordinates': [-74.015465, ..."
49,Starbucks,Brooklyn,"[-73.980887, 40.689304]","{'Type': 'Point', 'coordinates': [-73.980887, ..."

In [52]:
df_starbucks_SE = pb.obtenerTodo("Starbucks", "seattle")
df_starbucks_SE

,Name,City,Coordinates,Geometry
0,Starbucks,Seattle,"[-122.338784, 47.624406]","{'Type': 'Point', 'coordinates': [-122.338784,..."
1,Starbucks,Seattle,"[-122.33691, 47.62282]","{'Type': 'Point', 'coordinates': [-122.33691, ..."
2,Starbucks,Seattle,"[-122.338248, 47.621473]","{'Type': 'Point', 'coordinates': [-122.338248,..."
3,Starbucks,Seattle,"[-122.340027, 47.629924]","{'Type': 'Point', 'coordinates': [-122.340027,..."
4,Starbucks,Seattle,"[-122.34252, 47.6288488]","{'Type': 'Point', 'coordinates': [-122.34252, ..."
5,Starbucks,Seattle,"[-122.33734250808, 47.618155819043]","{'Type': 'Point', 'coordinates': [-122.3373425..."
6,Starbucks,Seattle,"[-122.34728, 47.624732]","{'Type': 'Point', 'coordinates': [-122.34728, ..."
7,Starbucks,Seattle,"[-122.324992, 47.619373]","{'Type': 'Point', 'coordinates': [-122.324992,..."
8,Starbucks,Seattle,"[-122.3296864, 47.61704708]","{'Type': 'Point', 'coordinates': [-122.3296864..."
9,Starbucks,Seattle,"[-122.336894, 47.615675]","{'Type': 'Point', 'coordinates': [-122.336894,..."
10,Starbucks,Seattle,"[-122.344456, 47.617041]","{'Type': 'Point', 'coordinates': [-122.344456,..."
11,Starbucks,Seattle,"[-122.320728, 47.623023]","{'Type': 'Point', 'coordinates': [-122.320728,..."
12,Starbucks,Seattle,"[-122.338094, 47.615217]","{'Type': 'Point', 'coordinates': [-122.338094,..."
13,Starbucks,Seattle,"[-122.335879, 47.614308]","{'Type': 'Point', 'coordinates': [-122.335879,..."
14,Starbucks,Seattle,"[-122.350775, 47.621039]","{'Type': 'Point', 'coordinates': [-122.350775,..."
15,Starbucks,Seattle,"[-122.336970165459, 47.613866]","{'Type': 'Point', 'coordinates': [-122.3369701..."
16,Starbucks,Seattle,"[-122.32104, 47.61887]","{'Type': 'Point', 'coordinates': [-122.32104, ..."
17,Starbucks,Seattle,"[-122.34224, 47.61401]","{'Type': 'Point', 'coordinates': [-122.34224, ..."
18,Starbucks,Seattle,"[-122.335597, 47.612588]","{'Type': 'Point', 'coordinates': [-122.335597,..."
19,Starbucks,Seattle,"[-122.33375, 47.612256]","{'Type': 'Point', 'coordinates': [-122.33375, ..."
20,Starbucks,Seattle,"[-122.33561, 47.61182]","{'Type': 'Point', 'coordinates': [-122.33561, ..."
21,Starbucks,Seattle,"[-122.34276, 47.612516]","{'Type': 'Point', 'coordinates': [-122.34276, ..."
22,Starbucks,Seattle,"[-122.34725, 47.613995]","{'Type': 'Point', 'coordinates': [-122.34725, ..."
23,Starbucks,Seattle,"[-122.337578, 47.611466]","{'Type': 'Point', 'coordinates': [-122.337578,..."
24,Starbucks,Seattle,"[-122.356896, 47.622947]","{'Type': 'Point', 'coordinates': [-122.356896,..."
25,Starbucks,Seattle,"[-122.33351, 47.61051]","{'Type': 'Point', 'coordinates': [-122.33351, ..."
26,Starbucks,Seattle,"[-122.3333673, 47.61072371]","{'Type': 'Point', 'coordinates': [-122.3333673..."
27,Starbucks,Seattle,"[-122.320995, 47.6142126]","{'Type': 'Point', 'coordinates': [-122.320995,..."
28,Starbucks,Seattle,"[-122.334698, 47.610526]","{'Type': 'Point', 'coordinates': [-122.334698,..."
29,Starbucks,Seattle,"[-122.33718, 47.610438]","{'Type': 'Point', 'coordinates': [-122.33718, ..."
30,Starbucks,Seattle,"[-122.321071, 47.613897]","{'Type': 'Point', 'coordinates': [-122.321071,..."
31,Starbucks,Seattle,"[-122.332429, 47.610279]","{'Type': 'Point', 'coordinates': [-122.332429,..."
32,Starbucks,Seattle,"[-122.333924, 47.610162]","{'Type': 'Point', 'coordinates': [-122.333924,..."
33,Starbucks,Seattle,"[-122.352021, 47.614129]","{'Type': 'Point', 'coordinates': [-122.352021,..."
34,Starbucks,Seattle,"[-122.337912, 47.609564]","{'Type': 'Point', 'coordinates': [-122.337912,..."
35,Starbucks,Seattle,"[-122.329025268555, 47.581657409668]","{'Type': 'Point', 'coordinates': [-122.3290252..."
36,Starbucks,Seattle,"[-122.342583, 47.610021]","{'Type': 'Point', 'coordinates': [-122.342583,..."
37,Starbucks,Seattle,"[-122.312953, 47.620152]","{'Type': 'Point', 'coordinates': [-122.312953,..."
38,Starbucks,Seattle,"[-122.339942, 47.609009]","{'Type': 'Point', 'coordinates': [-122.339942,..."
39,Starbucks,Seattle,"[-122.325643, 47.641048]","{'Type': 'Point', 'coordinates': [-122.325643,..."
40,Starbucks,Seattle,"[-122.338361, 47.608327]","{'Type': 'Point', 'coordinates': [-122.338361,..."
41,Starbucks,Seattle,"[-122.337863, 47.607773]","{'Type': 'Point', 'coordinates': [-122.337863,..."
42,Starbucks,Seattle,"[-122.324165, 47.609579]","{'Type': 'Point', 'coordinates': [-122.324165,..."
43,Starbucks,Seattle,"[-122.334259, 47.607304]","{'Type': 'Point', 'coordinates': [-122.334259,..."
44,Starbucks,Seattle,"[-122.335659, 47.607118]","{'Type': 'Point', 'coordinates': [-122.335659,..."
45,Starbucks Reserve,Seattle,"[-122.338599853967, 47.6069340167606]","{'Type': 'Point', 'coordinates': [-122.3385998..."
46,Starbucks,Seattle,"[-122.356255, 47.637801]","{'Type': 'Point', 'coordinates': [-122.356255,..."
47,Starbucks,Seattle,"[-122.336536, 47.606411]","{'Type': 'Point', 'coordinates': [-122.336536,..."
48,Starbucks,Seattle,"[-122.321584, 47.608774]","{'Type': 'Point', 'coordinates': [-122.321584,..."
49,Starbucks,Seattle,"[-122.357116, 47.638255]","{'Type': 'Point', 'coordinates': [-122.357116,..."

In [53]:

df_starbucks =df_starbucks_SN.append(df_starbucks_NY)

In [54]:
df_starbucks

,Name,City,Coordinates,Geometry
0,Starbucks,San Francisco,"[-122.434666, 37.761019]","{'Type': 'Point', 'coordinates': [-122.434666,..."
1,Starbucks,San Francisco,"[-122.431709, 37.751341]","{'Type': 'Point', 'coordinates': [-122.431709,..."
2,Starbucks,San Francisco,"[-122.428353, 37.769122]","{'Type': 'Point', 'coordinates': [-122.428353,..."
3,Starbucks,San Francisco,"[-122.456377, 37.7641418236607]","{'Type': 'Point', 'coordinates': [-122.456377,..."
4,Starbucks,San Francisco,"[-122.446293, 37.775737]","{'Type': 'Point', 'coordinates': [-122.446293,..."
...,...,...,...,...
45,Starbucks,New York,"[-74.015373, 40.710914]","{'Type': 'Point', 'coordinates': [-74.015373, ..."
46,Starbucks,New York,"[-73.997942, 40.722553]","{'Type': 'Point', 'coordinates': [-73.997942, ..."
47,Starbucks,Brooklyn,"[-73.98563, 40.68921]","{'Type': 'Point', 'coordinates': [-73.98563, 4..."
48,Starbucks Reserve,New York,"[-74.015465, 40.713821]","{'Type': 'Point', 'coordinates': [-74.015465, ..."
49,Starbucks,Brooklyn,"[-73.980887, 40.689304]","{'Type': 'Point', 'coordinates': [-73.980887, ..."

In [55]:
df_starbucks= df_starbucks.append(df_starbucks_SE)

In [56]:
df_starbucks

,Name,City,Coordinates,Geometry
0,Starbucks,San Francisco,"[-122.434666, 37.761019]","{'Type': 'Point', 'coordinates': [-122.434666,..."
1,Starbucks,San Francisco,"[-122.431709, 37.751341]","{'Type': 'Point', 'coordinates': [-122.431709,..."
2,Starbucks,San Francisco,"[-122.428353, 37.769122]","{'Type': 'Point', 'coordinates': [-122.428353,..."
3,Starbucks,San Francisco,"[-122.456377, 37.7641418236607]","{'Type': 'Point', 'coordinates': [-122.456377,..."
4,Starbucks,San Francisco,"[-122.446293, 37.775737]","{'Type': 'Point', 'coordinates': [-122.446293,..."
...,...,...,...,...
45,Starbucks Reserve,Seattle,"[-122.338599853967, 47.6069340167606]","{'Type': 'Point', 'coordinates': [-122.3385998..."
46,Starbucks,Seattle,"[-122.356255, 47.637801]","{'Type': 'Point', 'coordinates': [-122.356255,..."
47,Starbucks,Seattle,"[-122.336536, 47.606411]","{'Type': 'Point', 'coordinates': [-122.336536,..."
48,Starbucks,Seattle,"[-122.321584, 47.608774]","{'Type': 'Point', 'coordinates': [-122.321584,..."
49,Starbucks,Seattle,"[-122.357116, 47.638255]","{'Type': 'Point', 'coordinates': [-122.357116,..."

In [57]:
type(df_starbucks.to_dict('split'))

dict

In [58]:
df_starbucks

,Name,City,Coordinates,Geometry
0,Starbucks,San Francisco,"[-122.434666, 37.761019]","{'Type': 'Point', 'coordinates': [-122.434666,..."
1,Starbucks,San Francisco,"[-122.431709, 37.751341]","{'Type': 'Point', 'coordinates': [-122.431709,..."
2,Starbucks,San Francisco,"[-122.428353, 37.769122]","{'Type': 'Point', 'coordinates': [-122.428353,..."
3,Starbucks,San Francisco,"[-122.456377, 37.7641418236607]","{'Type': 'Point', 'coordinates': [-122.456377,..."
4,Starbucks,San Francisco,"[-122.446293, 37.775737]","{'Type': 'Point', 'coordinates': [-122.446293,..."
...,...,...,...,...
45,Starbucks Reserve,Seattle,"[-122.338599853967, 47.6069340167606]","{'Type': 'Point', 'coordinates': [-122.3385998..."
46,Starbucks,Seattle,"[-122.356255, 47.637801]","{'Type': 'Point', 'coordinates': [-122.356255,..."
47,Starbucks,Seattle,"[-122.336536, 47.606411]","{'Type': 'Point', 'coordinates': [-122.336536,..."
48,Starbucks,Seattle,"[-122.321584, 47.608774]","{'Type': 'Point', 'coordinates': [-122.321584,..."
49,Starbucks,Seattle,"[-122.357116, 47.638255]","{'Type': 'Point', 'coordinates': [-122.357116,..."

In [59]:
type(df_starbucks["Geometry"])

pandas.core.series.Series

In [62]:
import json
df_starbucks.to_json("./starbucks.json", orient = "records")

In [49]:
from pymongo import MongoClient
import pandas as pd
import json as js

mongo_client = MongoClient('localhost', 27017)

# create new database and client collection
db= mongo_client["companies"]

db.create_collection("starbucks")

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'companies'), 'starbucks')

TypeError: 'Series' object is not callable

In [ ]:
df_starbucks.to_csv("starbucks")

In [ ]:
# si quiero hacer muchos mas dataframes en vez de aplicar un append es mas eficiente aplicar un concat